/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wangmian_www_firstcpp_NativeHelper */

#ifndef _Included_wangmian_www_firstcpp_NativeHelper
#define _Included_wangmian_www_firstcpp_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wangmian_www_firstcpp_NativeHelper
 * Method:    hellocpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wangmian_www_firstcpp_NativeHelper_hellocpp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
